### ISSUE TITLE
How to test/play

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#20] opened 2016-08-06 12:43 UTC
Would be great to have some testing instructions or similar in the readme to get started with the project. Perhaps there are people coming here who want to contribute.

**Comment by dgt41** [comment] 2016-08-06 13:21
There are two ways to test any PR here:

- The easy one where you need to download a copy of this repo from (here)[https://github.com/joomla-projects/media-manager-improvement/archive/master.zip] and then install it locally. Also grab com_patchtester and install that too and then go to it's configuration options and set the project name to joomla-projects and the repo to media-manager-improvement
After that a fetch in the com_patchtester will show all the PRs and you can apply any of those and test it.

- The hard way needs some git commands where you get that repo locally and then switch to any branch. Again you will have to install it locally pointing your servers path to the folder that the local repo exists

**Comment by laoneo** [comment] 2016-08-06 13:49
I was asking more what todo after installation not how to install it. Also not how to test a pr more what to look for on this project.

**Comment by jissereitsma** [comment] 2016-08-06 14:07
Hi @laoneo , I think for now it is still a bit like having "loose ends". @marcodings and I will hopefully meet somewhere upcoming days, we have a small code sprint on August 13th (for which I'm supposed to some organizing, grrr) and will work on more features soon. As for now, real end-to-end testing is only needed sporadically, while the [wiki](https://github.com/joomla-projects/media-manager-improvement/wiki) is supposed to keep track of the subprojects still at hands. Let me know if you're interested in joining one of these subprojects, so I can keep you in the loop.

**Comment by laoneo** [comment] 2016-08-08 07:11
I think I an help out with Flysystem, as I did already a project with it, if needed.

**Comment by dgt41** [comment] 2016-08-08 08:39
@laoneo it will be great if we can have Flysystem.
Probably there will need to be some trick in the autoloader to skip it for PHP versions that are not supported (<5.5 I  think)

**Comment by jissereitsma** [comment] 2016-08-08 08:47
@laoneo @dgt41 Having more people on board with the FlySystem subproject is great. But please note that this has much less priority than the other points (as outlined in the wiki). The main point is indeed PHP compatibility, so FlySystem support will not be added until Joomla X comes out - at least it will not be included in the next Joomla release. The reason FlySystem was added as a subproject for the "short term" list was to make sure we make progress towards that integration (without actually integrating it). I hope I make some sense here ;)

**Comment by laoneo** [comment] 2016-08-08 09:39
So what's the most important features missing? Where do you need help specifically?

**Comment by jissereitsma** [comment] 2016-08-08 10:24
Well, actually all issues as documented in the [wiki](https://github.com/joomla-projects/media-manager-improvement/wiki) under "Pending (short term)" are important. However, the problem is that we are proposing some radical changes - mainly ditching folders in favor of categories (with folders attached to them). This will be a major change in the upcoming weeks, and only after that, I know more about which parts need to be picked up more specifically (and more practically). Great to have your input here anyway! And I'll be back with more news soon! (Let's keep this issue open as a reminder for me.)

**Comment by jissereitsma** [comment] 2016-08-10 15:57
I talked with @marcodings about you and your vibe and he'll be contacting you on a sprint this Saturday. We might need help with replacing `folders` with `categories` like in DP Fields. Closing this issue for the record.

**Closed by jissereitsma** 2016-08-10 15:57 UTC
