### ISSUE TITLE
"save as copy" button

### ISSUE THREAD

**Issue by micker** [joomla-projects/media-manager-improvement#476] opened 2017-11-21 19:42 UTC
i think we need a
"save as copy" button : when we rezize image we need to keep original image ... a simple save as copy can be good
maybe it will be a default button for all modifications

**Comment by laoneo** [comment] 2017-12-11 09:58
Sounds like a nice idea, somebody else was requesting that on twitter as well https://twitter.com/tbachner/status/939063238192435200

**Comment by laoneo** [comment] 2018-01-13 18:46
Closing this as duplicate of #385.

**Closed as completed** 2018-01-13 18:46 UTC
Labels: enhancement
