### ISSUE TITLE
Layout is messed up after the update

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#577] opened 2018-08-16 10:35 UTC
### Steps to reproduce the issue
- Pull from latest nmm dev branch
- Go to the Media Manager
- Click on item then go to edit

### Expected result
- It should display a correct edit view

### Actual result
- Edit view display multiple copies of the image(for all the tabs)
- Edit view has a layout issue, sidebar is not displaying correctly

![image](https://user-images.githubusercontent.com/13379595/44203797-f5137380-a16d-11e8-896a-55121576cca5.png)

![image](https://user-images.githubusercontent.com/13379595/44204068-dd88ba80-a16e-11e8-838b-b9f7106105c0.png)

### System information (as much as possible)
- Windows 10
- Docker php 7.2fpm
- Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by laoneo** [comment] 2018-08-17 06:51
I guess we need to wait till all the JS changes get into core like ES6 and the custom elements rewrite to get a fix for this issue.

**Comment by laoneo** [comment] 2018-08-22 12:26
I'v synced the media manager with upstream and it shows now only one image
![image](https://user-images.githubusercontent.com/251072/44461449-2ded9580-a611-11e8-9cd9-11c19e43fed2.png)

Before the tabs have been a custom element the controls have been on the sidebar. Now the code got changed the way that the image is moved inside the tabs. @dgrammatiko any idea how we can move them back to the sidebar?

**Comment by brianteeman** [comment] 2018-08-22 12:30
Not at my pc but try
Adding $this->useCoreUI = true;

—

**Comment by laoneo** [comment] 2018-08-22 12:32
We do that already here https://github.com/joomla-projects/media-manager-improvement/blob/dev/administrator/components/com_media/tmpl/file/default.php#L56.

**Comment by brianteeman** [comment] 2018-08-22 12:39
It was a guess as I am not at my pc.

**Comment by dgrammatiko** [comment] 2018-08-22 19:12
The logic of the edit-media.js needs to be adjusted. The old way was that the image **wasn't** part of the tabs (although it was rendered after the tabs navigation). This of course is broken now because of the new tabs design, and frankly because it was totally wrong to start with. So the methods activate and deactivate need to dynamically reposition the div (container) for the image. It's fairly easy task for anyone to do it

**Comment by geetanshu-m** [comment] 2018-08-25 14:28
@laoneo just pulled from the repo, fresh installed joomla, Still getting three images.

**Comment by laoneo** [comment] 2018-08-25 16:31
Any js error?

**Comment by geetanshu-m** [comment] 2018-08-25 21:37
No JS error is being reflected in console.

**Comment by TobsBobs** [comment] 2018-10-07 18:36
I can confirm this issue!

![screenshot_2018-10-07 media edit - joomla 4 test - administration](https://user-images.githubusercontent.com/816779/46585343-098a3300-ca70-11e8-89b0-fd8a69aa9066.jpg)

No JS error:

Gewechselt zu http://localhost/j4/administrator/index.php?option=com_media&view=file&path=local-0:/banners/banner.jpg
GEThttp://localhost/j4/administrator/index.php?option=com_media&view=file&path=local-0:/banners/banner.jpg
[HTTP/1.1 200 OK 625ms]
GEThttp://localhost/j4/media/vendor/cropperjs/css/cropper.min.css?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 4ms]
GEThttp://localhost/j4/media/com_media/css/mediamanager.min.css
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/vendor/joomla-custom-elements/css/joomla-tab.min.css?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 4ms]
GEThttp://localhost/j4/administrator/templates/atum/css/bootstrap.min.css?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/administrator/templates/atum/css/font-awesome.min.css?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/administrator/templates/atum/css/template.min.css?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/system/js/core.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/vendor/jquery/js/jquery.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/legacy/js/jquery-noconflict.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/vendor/bootstrap/js/bootstrap.bundle.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/legacy/js/bootstrap-init.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/vendor/joomla-custom-elements/css/joomla-alert.min.css?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 3ms]
GEThttp://localhost/j4/media/vendor/focus-visible/js/focus-visible.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/vendor/css-vars-ponyfill/js/css-vars-ponyfill.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/legacy/js/toolbar.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/mod_menu/js/admin-menu.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/plg_media-action_crop/js/crop.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 4ms]
GEThttp://localhost/j4/media/vendor/cropperjs/js/cropper.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 5ms]
GEThttp://localhost/j4/media/plg_media-action_resize/js/resize.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 4ms]
GEThttp://localhost/j4/media/plg_media-action_rotate/js/rotate.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 4ms]
GEThttp://localhost/j4/media/vendor/punycode/js/punycode.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 5ms]
GEThttp://localhost/j4/media/system/js/fields/validate.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 4ms]
GEThttp://localhost/j4/media/com_media/js/edit-images.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 3ms]
GEThttp://localhost/j4/media/vendor/joomla-custom-elements/js/joomla-tab.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 4ms]
GEThttp://localhost/j4/media/vendor/joomla-custom-elements/js/joomla-alert.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/system/webcomponents/js/joomla-toolbar-button.min.js?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 304 Not Modified 3ms]
GEThttp://localhost/j4/administrator/templates/atum/favicon.ico
[HTTP/1.1 200 OK 0ms]
GEThttp://localhost/j4/media/vendor/cropperjs/css/cropper.min.css?e5a3df7cce15a236c699547f776a6452
[HTTP/1.1 200 OK 0ms]

**Comment by kasvith** [comment] 2018-12-30 05:04
any update on fixing issue?

**Comment by uglyeoin** [comment] 2019-10-19 11:43
I no longer see this issue occuring.  Can this issue be closed?

**Comment by obuisard** [comment] 2019-10-19 14:14
I do not see any JavaScript error, it's good to go for me.

**Comment by uglyeoin** [comment] 2019-10-19 15:34
@obuisard you do not see duplicate images either right?  If that is correct this issue can be closed by @kasvith

**Comment by obuisard** [comment] 2019-10-19 15:49
No, no duplicates :-)

**Comment by uglyeoin** [comment] 2019-10-19 15:51
@kasvith thanks for reporting this issue.  It seems like a lot of people had it at the time but the issue has been resolved by someone along the way and it no longer exists.  As two people have tested this and agree, can you close the issue please?

**Closed as completed** 2019-10-19 20:56 UTC
Labels: bug, UX/UI
